# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `libev_scheduler` gem.
# Please instead update this file by running `bin/tapioca gem libev_scheduler`.

# source://libev_scheduler//lib/libev_scheduler.rb#3
module Libev; end

# source://libev_scheduler//lib/libev_scheduler.rb#4
class Libev::Scheduler
  def initialize; end

  def block(*_arg0); end
  def close; end

  # source://libev_scheduler//lib/libev_scheduler.rb#5
  def fiber(&block); end

  def io_wait(_arg0, _arg1, _arg2); end

  # source://libev_scheduler//lib/libev_scheduler.rb#12
  def kernel_sleep(duration = T.unsafe(nil)); end

  def pending_count; end

  # source://libev_scheduler//lib/libev_scheduler.rb#16
  def process_wait(pid, flags); end

  def run; end
  def unblock(_arg0, _arg1); end
end
