# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `progressbar` gem.
# Please instead update this file by running `bin/tapioca gem progressbar`.

# source://progressbar//lib/progressbar.rb#8
class ProgressBar
  class << self
    # source://progressbar//lib/progressbar.rb#9
    def create(*args); end
  end
end
